import csv

# Data from Bulbapedia and PokéDB
pokemon_data = [
    # (dex_number, species_name, form_name, type1, type2, generation, has_mega, mega_key)
    (3, "Venusaur", "", "grass", "poison", 1, True, "venusaur-mega"),
    (3, "Venusaur", "Mega Venusaur", "grass", "poison", 1, False, ""),
    (6, "Charizard", "", "fire", "flying", 1, True, "charizard-mega-x"),
    (6, "Charizard", "Mega Charizard X", "fire", "dragon", 1, False, ""),
    (6, "Charizard", "Mega Charizard Y", "fire", "flying", 1, False, ""),
    (9, "Blastoise", "", "water", "", 1, True, "blastoise-mega"),
    (9, "Blastoise", "Mega Blastoise", "water", "", 1, False, ""),
    (15, "Beedrill", "", "bug", "poison", 1, True, "beedrill-mega"),
    (15, "Beedrill", "Mega Beedrill", "bug", "poison", 1, False, ""),
    (18, "Pidgeot", "", "normal", "flying", 1, True, "pidgeot-mega"),
    (18, "Pidgeot", "Mega Pidgeot", "normal", "flying", 1, False, ""),
    (24, "Arbok", "", "poison", "", 1, False, ""),
    (25, "Pikachu", "", "electric", "", 1, False, ""),
    (26, "Raichu", "", "electric", "", 1, False, ""),
    (26, "Raichu", "Alolan Form", "electric", "psychic", 1, False, ""),
    (36, "Clefable", "", "fairy", "", 1, True, "clefable-mega"),
    (36, "Clefable", "Mega Clefable", "fairy", "flying", 1, False, ""),
    (38, "Ninetales", "", "fire", "", 1, False, ""),
    (38, "Ninetales", "Alolan Form", "ice", "fairy", 1, False, ""),
    (59, "Arcanine", "", "fire", "", 1, False, ""),
    (59, "Arcanine", "Hisuian Form", "fire", "rock", 1, False, ""),
    (65, "Alakazam", "", "psychic", "", 1, True, "alakazam-mega"),
    (65, "Alakazam", "Mega Alakazam", "psychic", "", 1, False, ""),
    (68, "Machamp", "", "fighting", "", 1, False, ""),
    (71, "Victreebel", "", "grass", "poison", 1, True, "victreebel-mega"),
    (71, "Victreebel", "Mega Victreebel", "grass", "poison", 1, False, ""),
    (80, "Slowbro", "", "water", "psychic", 1, True, "slowbro-mega"),
    (80, "Slowbro", "Mega Slowbro", "water", "psychic", 1, False, ""),
    (80, "Slowbro", "Galarian Form", "poison", "psychic", 1, False, ""),
    (94, "Gengar", "", "ghost", "poison", 1, True, "gengar-mega"),
    (94, "Gengar", "Mega Gengar", "ghost", "poison", 1, False, ""),
    (115, "Kangaskhan", "", "normal", "", 1, True, "kangaskhan-mega"),
    (115, "Kangaskhan", "Mega Kangaskhan", "normal", "", 1, False, ""),
    (121, "Starmie", "", "water", "psychic", 1, True, "starmie-mega"),
    (121, "Starmie", "Mega Starmie", "water", "psychic", 1, False, ""),
    (127, "Pinsir", "", "bug", "", 1, True, "pinsir-mega"),
    (127, "Pinsir", "Mega Pinsir", "bug", "flying", 1, False, ""),
    (128, "Tauros", "", "normal", "", 1, False, ""),
    (128, "Tauros", "Paldean Form Combat Breed", "fighting", "", 1, False, ""),
    (128, "Tauros", "Paldean Form Blaze Breed", "fighting", "fire", 1, False, ""),
    (128, "Tauros", "Paldean Form Aqua Breed", "fighting", "water", 1, False, ""),
    (130, "Gyarados", "", "water", "flying", 1, True, "gyarados-mega"),
    (130, "Gyarados", "Mega Gyarados", "water", "dark", 1, False, ""),
    (132, "Ditto", "", "normal", "", 1, False, ""),
    (134, "Vaporeon", "", "water", "", 1, False, ""),
    (135, "Jolteon", "", "electric", "", 1, False, ""),
    (136, "Flareon", "", "fire", "", 1, False, ""),
    (142, "Aerodactyl", "", "rock", "flying", 1, True, "aerodactyl-mega"),
    (142, "Aerodactyl", "Mega Aerodactyl", "rock", "flying", 1, False, ""),
    (143, "Snorlax", "", "normal", "", 1, False, ""),
    (149, "Dragonite", "", "dragon", "flying", 1, True, "dragonite-mega"),
    (149, "Dragonite", "Mega Dragonite", "dragon", "flying", 1, False, ""),
    (154, "Meganium", "", "grass", "", 2, True, "meganium-mega"),
    (154, "Meganium", "Mega Meganium", "grass", "fairy", 2, False, ""),
    (157, "Typhlosion", "", "fire", "", 2, False, ""),
    (157, "Typhlosion", "Hisuian Form", "fire", "ghost", 2, False, ""),
    (160, "Feraligatr", "", "water", "", 2, True, "feraligatr-mega"),
    (160, "Feraligatr", "Mega Feraligatr", "water", "dragon", 2, False, ""),
    (168, "Ariados", "", "bug", "poison", 2, False, ""),
    (181, "Ampharos", "", "electric", "", 2, True, "ampharos-mega"),
    (181, "Ampharos", "Mega Ampharos", "electric", "dragon", 2, False, ""),
    (184, "Azumarill", "", "water", "fairy", 2, False, ""),
    (186, "Politoed", "", "water", "", 2, False, ""),
    (196, "Espeon", "", "psychic", "", 2, False, ""),
    (197, "Umbreon", "", "dark", "", 2, False, ""),
    (199, "Slowking", "", "water", "psychic", 2, False, ""),
    (199, "Slowking", "Galarian Form", "poison", "psychic", 2, False, ""),
    (205, "Forretress", "", "bug", "steel", 2, False, ""),
    (208, "Steelix", "", "steel", "ground", 2, True, "steelix-mega"),
    (208, "Steelix", "Mega Steelix", "steel", "ground", 2, False, ""),
    (212, "Scizor", "", "bug", "steel", 2, True, "scizor-mega"),
    (212, "Scizor", "Mega Scizor", "bug", "steel", 2, False, ""),
    (214, "Heracross", "", "bug", "fighting", 2, True, "heracross-mega"),
    (214, "Heracross", "Mega Heracross", "bug", "fighting", 2, False, ""),
    (227, "Skarmory", "", "steel", "flying", 2, True, "skarmory-mega"),
    (227, "Skarmory", "Mega Skarmory", "steel", "flying", 2, False, ""),
    (229, "Houndoom", "", "dark", "fire", 2, True, "houndoom-mega"),
    (229, "Houndoom", "Mega Houndoom", "dark", "fire", 2, False, ""),
    (248, "Tyranitar", "", "rock", "dark", 2, True, "tyranitar-mega"),
    (248, "Tyranitar", "Mega Tyranitar", "rock", "dark", 2, False, ""),
    (279, "Pelipper", "", "water", "flying", 3, False, ""),
    (282, "Gardevoir", "", "psychic", "fairy", 3, True, "gardevoir-mega"),
    (282, "Gardevoir", "Mega Gardevoir", "psychic", "fairy", 3, False, ""),
    (302, "Sableye", "", "dark", "ghost", 3, True, "sableye-mega"),
    (302, "Sableye", "Mega Sableye", "dark", "ghost", 3, False, ""),
    (306, "Aggron", "", "steel", "rock", 3, True, "aggron-mega"),
    (306, "Aggron", "Mega Aggron", "steel", "", 3, False, ""),
    (308, "Medicham", "", "fighting", "psychic", 3, True, "medicham-mega"),
    (308, "Medicham", "Mega Medicham", "fighting", "psychic", 3, False, ""),
    (310, "Manectric", "", "electric", "", 3, True, "manectric-mega"),
    (310, "Manectric", "Mega Manectric", "electric", "", 3, False, ""),
    (319, "Sharpedo", "", "water", "dark", 3, True, "sharpedo-mega"),
    (319, "Sharpedo", "Mega Sharpedo", "water", "dark", 3, False, ""),
    (323, "Camerupt", "", "fire", "ground", 3, True, "camerupt-mega"),
    (323, "Camerupt", "Mega Camerupt", "fire", "ground", 3, False, ""),
    (324, "Torkoal", "", "fire", "", 3, False, ""),
    (334, "Altaria", "", "dragon", "flying", 3, True, "altaria-mega"),
    (334, "Altaria", "Mega Altaria", "dragon", "fairy", 3, False, ""),
    (350, "Milotic", "", "water", "", 3, False, ""),
    (351, "Castform", "", "normal", "", 3, False, ""),
    (351, "Castform", "Sunny Form", "fire", "", 3, False, ""),
    (351, "Castform", "Rainy Form", "water", "", 3, False, ""),
    (351, "Castform", "Snowy Form", "ice", "", 3, False, ""),
    (354, "Banette", "", "ghost", "", 3, True, "banette-mega"),
    (354, "Banette", "Mega Banette", "ghost", "", 3, False, ""),
    (358, "Chimecho", "", "psychic", "", 3, True, "chimecho-mega"),
    (358, "Chimecho", "Mega Chimecho", "psychic", "steel", 3, False, ""),
    (359, "Absol", "", "dark", "", 3, True, "absol-mega"),
    (359, "Absol", "Mega Absol", "dark", "", 3, False, ""),
    (362, "Glalie", "", "ice", "", 3, True, "glalie-mega"),
    (362, "Glalie", "Mega Glalie", "ice", "", 3, False, ""),
    (389, "Torterra", "", "grass", "ground", 4, False, ""),
    (392, "Infernape", "", "fire", "fighting", 4, False, ""),
    (395, "Empoleon", "", "water", "steel", 4, False, ""),
    (405, "Luxray", "", "electric", "", 4, False, ""),
    (407, "Roserade", "", "grass", "poison", 4, False, ""),
    (409, "Rampardos", "", "rock", "", 4, False, ""),
    (411, "Bastiodon", "", "rock", "steel", 4, False, ""),
    (428, "Lopunny", "", "normal", "", 4, True, "lopunny-mega"),
    (428, "Lopunny", "Mega Lopunny", "normal", "fighting", 4, False, ""),
    (442, "Spiritomb", "", "ghost", "dark", 4, False, ""),
    (445, "Garchomp", "", "dragon", "ground", 4, True, "garchomp-mega"),
    (445, "Garchomp", "Mega Garchomp", "dragon", "ground", 4, False, ""),
    (448, "Lucario", "", "fighting", "steel", 4, True, "lucario-mega"),
    (448, "Lucario", "Mega Lucario", "fighting", "steel", 4, False, ""),
    (450, "Hippowdon", "", "ground", "", 4, False, ""),
    (454, "Toxicroak", "", "poison", "fighting", 4, False, ""),
    (460, "Abomasnow", "", "grass", "ice", 4, True, "abomasnow-mega"),
    (460, "Abomasnow", "Mega Abomasnow", "grass", "ice", 4, False, ""),
    (461, "Weavile", "", "dark", "ice", 4, False, ""),
    (464, "Rhyperior", "", "ground", "rock", 4, False, ""),
    (470, "Leafeon", "", "grass", "", 4, False, ""),
    (471, "Glaceon", "", "ice", "", 4, False, ""),
    (472, "Gliscor", "", "ground", "flying", 4, False, ""),
    (473, "Mamoswine", "", "ice", "ground", 4, False, ""),
    (475, "Gallade", "", "psychic", "fighting", 4, True, "gallade-mega"),
    (475, "Gallade", "Mega Gallade", "psychic", "fighting", 4, False, ""),
    (478, "Froslass", "", "ice", "ghost", 4, True, "froslass-mega"),
    (478, "Froslass", "Mega Froslass", "ice", "ghost", 4, False, ""),
    (479, "Rotom", "Rotom", "electric", "ghost", 4, False, ""),
    (479, "Rotom", "Heat Rotom", "electric", "fire", 4, False, ""),
    (479, "Rotom", "Wash Rotom", "electric", "water", 4, False, ""),
    (479, "Rotom", "Frost Rotom", "electric", "ice", 4, False, ""),
    (479, "Rotom", "Fan Rotom", "electric", "flying", 4, False, ""),
    (479, "Rotom", "Mow Rotom", "electric", "grass", 4, False, ""),
    (497, "Serperior", "", "grass", "", 5, False, ""),
    (500, "Emboar", "", "fire", "fighting", 5, True, "emboar-mega"),
    (500, "Emboar", "Mega Emboar", "fire", "fighting", 5, False, ""),
    (503, "Samurott", "", "water", "", 5, False, ""),
    (503, "Samurott", "Hisuian Form", "water", "dark", 5, False, ""),
    (505, "Watchog", "", "normal", "", 5, False, ""),
    (510, "Liepard", "", "dark", "", 5, False, ""),
    (512, "Simisage", "", "grass", "", 5, False, ""),
    (514, "Simisear", "", "fire", "", 5, False, ""),
    (516, "Simipour", "", "water", "", 5, False, ""),
    (530, "Excadrill", "", "ground", "steel", 5, True, "excadrill-mega"),
    (530, "Excadrill", "Mega Excadrill", "ground", "steel", 5, False, ""),
    (531, "Audino", "", "normal", "", 5, True, "audino-mega"),
    (531, "Audino", "Mega Audino", "normal", "fairy", 5, False, ""),
    (534, "Conkeldurr", "", "fighting", "", 5, False, ""),
    (547, "Whimsicott", "", "grass", "fairy", 5, False, ""),
    (553, "Krookodile", "", "ground", "dark", 5, False, ""),
    (563, "Cofagrigus", "", "ghost", "", 5, False, ""),
    (569, "Garbodor", "", "poison", "", 5, False, ""),
    (571, "Zoroark", "", "dark", "", 5, False, ""),
    (571, "Zoroark", "Hisuian Form", "normal", "ghost", 5, False, ""),
    (579, "Reuniclus", "", "psychic", "", 5, False, ""),
    (584, "Vanilluxe", "", "ice", "", 5, False, ""),
    (587, "Emolga", "", "electric", "flying", 5, False, ""),
    (609, "Chandelure", "", "ghost", "fire", 5, True, "chandelure-mega"),
    (609, "Chandelure", "Mega Chandelure", "ghost", "fire", 5, False, ""),
    (614, "Beartic", "", "ice", "", 5, False, ""),
    (618, "Stunfisk", "", "ground", "electric", 5, False, ""),
    (618, "Stunfisk", "Galarian Form", "ground", "steel", 5, False, ""),
    (623, "Golurk", "", "ground", "ghost", 5, True, "golurk-mega"),
    (623, "Golurk", "Mega Golurk", "ground", "ghost", 5, False, ""),
    (635, "Hydreigon", "", "dark", "dragon", 5, False, ""),
    (637, "Volcarona", "", "bug", "fire", 5, False, ""),
    (652, "Chesnaught", "", "grass", "fighting", 6, True, "chesnaught-mega"),
    (652, "Chesnaught", "Mega Chesnaught", "grass", "fighting", 6, False, ""),
    (655, "Delphox", "", "fire", "psychic", 6, True, "delphox-mega"),
    (655, "Delphox", "Mega Delphox", "fire", "psychic", 6, False, ""),
    (658, "Greninja", "", "water", "dark", 6, True, "greninja-mega"),
    (658, "Greninja", "Mega Greninja", "water", "dark", 6, False, ""),
    (660, "Diggersby", "", "normal", "ground", 6, False, ""),
    (663, "Talonflame", "", "fire", "flying", 6, False, ""),
    (666, "Vivillon", "", "bug", "flying", 6, False, ""),
    (666, "Vivillon", "Icy Snow Pattern", "bug", "flying", 6, False, ""),
    (666, "Vivillon", "Polar Pattern", "bug", "flying", 6, False, ""),
    (666, "Vivillon", "Tundra Pattern", "bug", "flying", 6, False, ""),
    (666, "Vivillon", "Continental Pattern", "bug", "flying", 6, False, ""),
    (666, "Vivillon", "Garden Pattern", "bug", "flying", 6, False, ""),
    (666, "Vivillon", "Elegant Pattern", "bug", "flying", 6, False, ""),
    (666, "Vivillon", "Meadow Pattern", "bug", "flying", 6, False, ""),
    (666, "Vivillon", "Modern Pattern", "bug", "flying", 6, False, ""),
    (666, "Vivillon", "Marine Pattern", "bug", "flying", 6, False, ""),
    (666, "Vivillon", "Archipelago Pattern", "bug", "flying", 6, False, ""),
    (666, "Vivillon", "High Plains Pattern", "bug", "flying", 6, False, ""),
    (666, "Vivillon", "Sandstorm Pattern", "bug", "flying", 6, False, ""),
    (666, "Vivillon", "River Pattern", "bug", "flying", 6, False, ""),
    (666, "Vivillon", "Monsoon Pattern", "bug", "flying", 6, False, ""),
    (666, "Vivillon", "Savanna Pattern", "bug", "flying", 6, False, ""),
    (666, "Vivillon", "Sun Pattern", "bug", "flying", 6, False, ""),
    (666, "Vivillon", "Ocean Pattern", "bug", "flying", 6, False, ""),
    (666, "Vivillon", "Jungle Pattern", "bug", "flying", 6, False, ""),
    (666, "Vivillon", "Poké Ball Pattern", "bug", "flying", 6, False, ""),
    (670, "Floette", "", "fairy", "", 6, False, ""),
    (670, "Floette", "Eternal Flower", "fairy", "", 6, True, "floette-mega"),
    (670, "Floette", "Mega Floette", "fairy", "", 6, False, ""),
    (671, "Florges", "", "fairy", "", 6, False, ""),
    (671, "Florges", "Yellow Flower", "fairy", "", 6, False, ""),
    (671, "Florges", "Orange Flower", "fairy", "", 6, False, ""),
    (671, "Florges", "Blue Flower", "fairy", "", 6, False, ""),
    (671, "Florges", "White Flower", "fairy", "", 6, False, ""),
    (675, "Pangoro", "", "fighting", "dark", 6, False, ""),
    (676, "Furfrou", "", "normal", "", 6, False, ""),
    (676, "Furfrou", "Heart Trim", "normal", "", 6, False, ""),
    (676, "Furfrou", "Star Trim", "normal", "", 6, False, ""),
    (676, "Furfrou", "Diamond Trim", "normal", "", 6, False, ""),
    (676, "Furfrou", "Debutante Trim", "normal", "", 6, False, ""),
    (676, "Furfrou", "Matron Trim", "normal", "", 6, False, ""),
    (676, "Furfrou", "Dandy Trim", "normal", "", 6, False, ""),
    (676, "Furfrou", "La Reine Trim", "normal", "", 6, False, ""),
    (676, "Furfrou", "Kabuki Trim", "normal", "", 6, False, ""),
    (676, "Furfrou", "Pharaoh Trim", "normal", "", 6, False, ""),
    (678, "Meowstic", "Male", "psychic", "", 6, True, "meowstic-mega"),
    (678, "Meowstic", "Female", "psychic", "", 6, True, "meowstic-mega"),
    (678, "Meowstic", "Mega Meowstic", "psychic", "", 6, False, ""),
    (681, "Aegislash", "", "steel", "ghost", 6, False, ""),
    (681, "Aegislash", "Blade Forme", "steel", "ghost", 6, False, ""),
    (683, "Aromatisse", "", "fairy", "", 6, False, ""),
    (685, "Slurpuff", "", "fairy", "", 6, False, ""),
    (693, "Clawitzer", "", "water", "", 6, False, ""),
    (695, "Heliolisk", "", "electric", "normal", 6, False, ""),
    (697, "Tyrantrum", "", "rock", "dragon", 6, False, ""),
    (699, "Aurorus", "", "rock", "ice", 6, False, ""),
    (700, "Sylveon", "", "fairy", "", 6, False, ""),
    (701, "Hawlucha", "", "fighting", "flying", 6, True, "hawlucha-mega"),
    (701, "Hawlucha", "Mega Hawlucha", "fighting", "flying", 6, False, ""),
    (702, "Dedenne", "", "electric", "fairy", 6, False, ""),
    (706, "Goodra", "", "dragon", "", 6, False, ""),
    (706, "Goodra", "Hisuian Form", "steel", "dragon", 6, False, ""),
    (707, "Klefki", "", "steel", "fairy", 6, False, ""),
    (709, "Trevenant", "", "ghost", "grass", 6, False, ""),
    (711, "Gourgeist", "Medium Variety", "ghost", "grass", 6, False, ""),
    (711, "Gourgeist", "Small Variety", "ghost", "grass", 6, False, ""),
    (711, "Gourgeist", "Large Variety", "ghost", "grass", 6, False, ""),
    (711, "Gourgeist", "Jumbo Variety", "ghost", "grass", 6, False, ""),
    (713, "Avalugg", "", "ice", "", 6, False, ""),
    (713, "Avalugg", "Hisuian Form", "ice", "rock", 6, False, ""),
    (715, "Noivern", "", "flying", "dragon", 6, False, ""),
    (724, "Decidueye", "", "grass", "ghost", 7, False, ""),
    (724, "Decidueye", "Hisuian Form", "grass", "fighting", 7, False, ""),
    (727, "Incineroar", "", "fire", "dark", 7, False, ""),
    (730, "Primarina", "", "water", "fairy", 7, False, ""),
    (733, "Toucannon", "", "normal", "flying", 7, False, ""),
    (740, "Crabominable", "", "fighting", "ice", 7, True, "crabominable-mega"),
    (740, "Crabominable", "Mega Crabominable", "fighting", "ice", 7, False, ""),
    (745, "Lycanroc", "Midday Form", "rock", "", 7, False, ""),
    (745, "Lycanroc", "Midnight Form", "rock", "", 7, False, ""),
    (745, "Lycanroc", "Dusk Form", "rock", "", 7, False, ""),
    (748, "Toxapex", "", "poison", "water", 7, False, ""),
    (750, "Mudsdale", "", "ground", "", 7, False, ""),
    (752, "Araquanid", "", "water", "bug", 7, False, ""),
    (758, "Salazzle", "", "poison", "fire", 7, False, ""),
    (763, "Tsareena", "", "grass", "", 7, False, ""),
    (765, "Oranguru", "", "normal", "psychic", 7, False, ""),
    (766, "Passimian", "", "fighting", "", 7, False, ""),
    (778, "Mimikyu", "", "ghost", "fairy", 7, False, ""),
    (780, "Drampa", "", "normal", "dragon", 7, True, "drampa-mega"),
    (780, "Drampa", "Mega Drampa", "normal", "dragon", 7, False, ""),
    (784, "Kommo-o", "", "dragon", "fighting", 7, False, ""),
    (823, "Corviknight", "", "flying", "steel", 7, False, ""),
    (841, "Flapple", "", "grass", "dragon", 8, False, ""),
    (842, "Appletun", "", "grass", "dragon", 8, False, ""),
    (844, "Sandaconda", "", "ground", "", 8, False, ""),
    (855, "Polteageist", "", "ghost", "", 8, False, ""),
    (858, "Hatterene", "", "psychic", "fairy", 8, False, ""),
    (866, "Mr. Rime", "", "ice", "psychic", 8, False, ""),
    (867, "Runerigus", "", "ground", "ghost", 8, False, ""),
    (869, "Alcremie", "", "fairy", "", 8, False, ""),
    (869, "Alcremie", "Ruby Cream", "fairy", "", 8, False, ""),
    (869, "Alcremie", "Matcha Cream", "fairy", "", 8, False, ""),
    (869, "Alcremie", "Mint Cream", "fairy", "", 8, False, ""),
    (869, "Alcremie", "Lemon Cream", "fairy", "", 8, False, ""),
    (869, "Alcremie", "Salted Cream", "fairy", "", 8, False, ""),
    (869, "Alcremie", "Ruby Swirl", "fairy", "", 8, False, ""),
    (869, "Alcremie", "Caramel Swirl", "fairy", "", 8, False, ""),
    (869, "Alcremie", "Rainbow Swirl", "fairy", "", 8, False, ""),
    (877, "Morpeko", "", "electric", "dark", 8, False, ""),
    (877, "Morpeko", "Hangry Mode", "electric", "dark", 8, False, ""),
    (887, "Dragapult", "", "dragon", "ghost", 8, False, ""),
    (899, "Wyrdeer", "", "normal", "psychic", 8, False, ""),
    (900, "Kleavor", "", "bug", "rock", 8, False, ""),
    (902, "Basculegion", "Male", "water", "ghost", 8, False, ""),
    (902, "Basculegion", "Female", "water", "ghost", 8, False, ""),
    (903, "Sneasler", "", "fighting", "poison", 8, False, ""),
    (908, "Meowscarada", "", "grass", "dark", 9, False, ""),
    (911, "Skeledirge", "", "fire", "ghost", 9, False, ""),
    (914, "Quaquaval", "", "water", "fighting", 9, False, ""),
    (925, "Maushold", "", "normal", "", 9, False, ""),
    (925, "Maushold", "Family of Four", "normal", "", 9, False, ""),
    (934, "Garganacl", "", "rock", "", 9, False, ""),
    (936, "Armarouge", "", "fire", "psychic", 9, False, ""),
    (937, "Ceruledge", "", "fire", "ghost", 9, False, ""),
    (939, "Bellibolt", "", "electric", "", 9, False, ""),
    (952, "Scovillain", "", "grass", "fire", 9, True, "scovillain-mega"),
    (952, "Scovillain", "Mega Scovillain", "grass", "fire", 9, False, ""),
    (956, "Espathra", "", "psychic", "", 9, False, ""),
    (959, "Tinkaton", "", "fairy", "steel", 9, False, ""),
    (964, "Palafin", "", "water", "", 9, False, ""),
    (964, "Palafin", "Hero Form", "water", "", 9, False, ""),
    (968, "Orthworm", "", "steel", "", 9, False, ""),
    (970, "Glimmora", "", "rock", "poison", 9, True, "glimmora-mega"),
    (970, "Glimmora", "Mega Glimmora", "rock", "poison", 9, False, ""),
    (981, "Farigiraf", "", "normal", "psychic", 9, False, ""),
    (983, "Kingambit", "", "dark", "steel", 9, False, ""),
    (1013, "Sinistcha", "", "grass", "ghost", 9, False, ""),
    (1018, "Archaludon", "", "steel", "dragon", 9, False, ""),
    (1019, "Hydrapple", "", "grass", "dragon", 9, False, ""),
]

stats_data = {
    (3, ""): (80, 82, 83, 100, 100, 80),
    (6, ""): (78, 84, 78, 109, 85, 100),
    (9, ""): (79, 83, 100, 85, 105, 78),
    (15, ""): (65, 90, 40, 45, 80, 75),
    (18, ""): (83, 80, 75, 70, 70, 101),
    (24, ""): (60, 95, 69, 65, 79, 80),
    (25, ""): (35, 55, 40, 50, 50, 90),
    (26, ""): (60, 90, 55, 90, 80, 110),
    (26, "Alolan"): (60, 85, 50, 95, 85, 110),
    (36, ""): (95, 70, 73, 95, 90, 60),
    (38, ""): (73, 76, 75, 81, 100, 100),
    (38, "Alolan"): (73, 67, 75, 81, 100, 109),
    (59, ""): (90, 110, 80, 100, 80, 95),
    (59, "Hisuian"): (95, 115, 80, 95, 80, 90),
    (65, ""): (55, 50, 45, 135, 95, 120),
    (68, ""): (90, 130, 80, 65, 85, 55),
    (71, ""): (80, 105, 65, 100, 70, 70),
    (80, ""): (95, 75, 110, 100, 80, 30),
    (80, "Galarian"): (95, 100, 95, 100, 70, 30),
    (94, ""): (60, 65, 60, 130, 75, 110),
    (115, ""): (105, 95, 80, 40, 80, 90),
    (121, ""): (60, 75, 85, 100, 85, 115),
    (127, ""): (65, 125, 100, 55, 70, 85),
    (128, ""): (75, 100, 95, 40, 70, 110),
    (128, "Paldean Combat Breed"): (75, 110, 105, 30, 70, 100),
    (128, "Paldean Blaze Breed"): (75, 110, 105, 30, 70, 100),
    (128, "Paldean Aqua Breed"): (75, 110, 105, 30, 70, 100),
    (130, ""): (95, 125, 79, 60, 100, 81),
    (132, ""): (48, 48, 48, 48, 48, 48),
    (134, ""): (130, 65, 60, 110, 95, 65),
    (135, ""): (65, 65, 60, 110, 95, 130),
    (136, ""): (65, 130, 60, 95, 110, 65),
    (142, ""): (80, 105, 65, 60, 75, 130),
    (143, ""): (160, 110, 65, 65, 110, 30),
    (149, ""): (91, 134, 95, 100, 100, 80),
    (154, ""): (80, 82, 100, 83, 100, 80),
    (157, ""): (78, 84, 78, 109, 85, 100),
    (157, "Hisuian"): (73, 84, 78, 119, 85, 95),
    (160, ""): (85, 105, 100, 79, 83, 78),
    (168, ""): (70, 90, 70, 60, 70, 40),
    (184, ""): (100, 50, 80, 60, 80, 50),
    # Add more stats
}

# Generate pokemon.csv
with open('data_raw/pokemon.csv', 'w', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerow(['pokemon_id', 'dex_number', 'species_key', 'form_key', 'name_en', 'name_es', 'form_name_en', 'form_name_es', 'type1_key', 'type2_key', 'generation', 'is_legendary', 'is_mythical', 'has_mega', 'mega_key', 'is_currently_legal', 'season_key', 'tier_current', 'tier_source_key', 'roster_source_key', 'format_availability', 'notes'])
    for i, (dex, name, form, t1, t2, gen, has_mega, mega) in enumerate(pokemon_data, 1):
        species_key = name.lower()
        form_key = form.lower().replace(' ', '-') if form else ''
        name_es = name  # Simplified
        form_name_en = form
        form_name_es = form
        type1_key = t1
        type2_key = t2
        has_mega = 1 if has_mega else 0
        mega_key = mega
        writer.writerow(['', dex, species_key, form_key, name, name_es, form_name_en, form_name_es, type1_key, type2_key, gen, 0, 0, has_mega, mega_key, 1, 'current', '', '', 'bulbapedia', 'standard', ''])

# Generate stats_base.csv
with open('data_raw/stats_base.csv', 'w', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerow(['pokemon_id', 'hp', 'attack', 'defense', 'sp_attack', 'sp_defense', 'speed'])
    for i, (dex, name, form, t1, t2, gen, has_mega, mega) in enumerate(pokemon_data, 1):
        if (dex, form) in stats_data:
            hp, atk, def_, spa, spd, spe = stats_data[(dex, form)]
            writer.writerow([i, hp, atk, def_, spa, spd, spe])

print("CSVs generated.")